version: "3"

services:
  db:
    image: mysql:5.7
    ports:
      - "3309:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: asdd
      MYSQL_DATABASE: si_lele

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:8080"
    command: bash -c
      "
      chmod 777 start.sh &&
      dos2unix start.sh  &&
      ./start.sh
      "  
