version: "3"

services:
  db:
    image: mysql:8
    ports:
      - "3309:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: asdd
      MYSQL_DATABASE: si_lele
      MYSQL_PASSWORD: asdd

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: asdd
