name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /var/www/api.pakar.farhandev.cloud
            docker rm -f skripsi-be
            docker build -t skripsi-be .
            docker run -d --name skripsi-be -p 3003:8080 skripsi-be
            docker images | grep '<none>' | awk '{print $3}' | xargs docker rmi
